language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     # You can uncomment this to explicitly choose an (old) version of the Arduino IDE
     #- ARDUINO_IDE_VERSION="1.8.7"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  # Note that every library should be installed in a seperate command
  - if [ ! -d "$HOME/arduino_ide/libraries/LibAPRS" ]; then git clone https://github.com/billygr/LibAPRS $HOME/arduino_ide/libraries/LibAPRS; fi
  - if [ ! -d "$HOME/arduino_ide/libraries/SimpleTimer" ]; then git clone https://github.com/jfturcot/SimpleTimer $HOME/arduino_ide/libraries/SimpleTimer; fi
  - if [ ! -d "$HOME/arduino_ide/libraries/TinyGPS" ]; then git clone https://github.com/mikalhart/TinyGPS $HOME/arduino_ide/libraries/TinyGPS; fi
  - if [ ! -d "$HOME/arduino_ide/libraries/TinyGPSPlus" ]; then git clone https://github.com/mikalhart/TinyGPSPlus $HOME/arduino_ide/libraries/TinyGPSPlus; fi
script:
  - build_platform uno
notifications:
  email:
    on_success: change
    on_failure: change
